### PR TITLE
chore: switch to svelte-eslint and update svelte version

### PR DESCRIPTION
**Pull request by olafurw**
[eslint-plugin-svelte3](https://github.com/sveltejs/eslint-plugin-svelte3) asks people to use [eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte). So I switched to that version.

Also updated Svelte to 4.2.0

### CODE REVIEW

**Review by colinlienard — CHANGES_REQUESTED** [review]
Looks like you didn't commit the changes on `pnpm-lock.yaml`, could you please do it?
Or run `pnpm install` and then commit the changes

**Comment by olafurw** [comment]
Added.

**Comment by olafurw** [comment]
Linting fix, give me a few. I also saw another issue from the eslint change that might be a false positive.

**Comment by olafurw** [comment]
Apparently since you define a parser you need to specify to use the svelte-eslint-parser for svelte files, otherwise it yelled about bad syntax in svelte files.

And I silenced self assignment (which was happening in 2 files) and the `$$Generic` usage since the RFC is technically not approved.

**Pull request merged**
